AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for URL Watcher SMS notifications using SNS'

Parameters:
  PhoneNumber:
    Type: String
    Description: 'Phone number for SMS notifications (format: +1234567890)'
    AllowedPattern: '^\+[1-9]\d{1,14}$'
    ConstraintDescription: 'Must be a valid phone number in E.164 format (e.g., +1234567890)'
  
  TopicName:
    Type: String
    Default: 'url-watcher-notifications'
    Description: 'Name for the SNS topic'
    AllowedPattern: '^[a-zA-Z0-9_-]+$'
    ConstraintDescription: 'Must contain only alphanumeric characters, hyphens, and underscores'

Resources:
  # SNS Topic for URL change notifications
  URLWatcherTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: 'URL Watcher Notifications'
      
  # SNS Subscription for SMS
  SMSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: 'sms'
      TopicArn: !Ref URLWatcherTopic
      Endpoint: !Ref PhoneNumber

  # IAM User for programmatic access to SNS
  URLWatcherUser:
    Type: AWS::IAM::User
    Properties:
      UserName: 'url-watcher-sns-user'
      Policies:
        - PolicyName: 'SNSPublishPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sns:Publish'
                Resource: !Ref URLWatcherTopic

  # Access Key for the IAM User
  URLWatcherAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref URLWatcherUser

Outputs:
  TopicArn:
    Description: 'ARN of the SNS topic'
    Value: !Ref URLWatcherTopic
    Export:
      Name: !Sub '${AWS::StackName}-TopicArn'
  
  AccessKeyId:
    Description: 'Access Key ID for the IAM user'
    Value: !Ref URLWatcherAccessKey
    
  SecretAccessKey:
    Description: 'Secret Access Key for the IAM user (store securely)'
    Value: !GetAtt URLWatcherAccessKey.SecretAccessKey
    NoEcho: true
  
  PhoneNumber:
    Description: 'Configured phone number for SMS notifications'
    Value: !Ref PhoneNumber